// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220622151735_RemovedColumns")]
    partial class RemovedColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Domain.BowlingGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BowlingGames");
                });

            modelBuilder.Entity("Domain.Frame", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BowlingGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdRoll")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "BowlingGameId", "FrameNumber");

                    b.HasIndex("BowlingGameId");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Frame", b =>
                {
                    b.HasOne("Domain.BowlingGame", "BowlingGame")
                        .WithMany("Frames")
                        .HasForeignKey("BowlingGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Frames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BowlingGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.BowlingGame", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
