// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220620204732_AddedColumnThirdRoll")]
    partial class AddedColumnThirdRoll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Domain.BowlingGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BowlingGames");
                });

            modelBuilder.Entity("Domain.Frame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BowlingGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondRoll")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThirdRoll")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BowlingGameId");

                    b.ToTable("Frame");
                });

            modelBuilder.Entity("Domain.Frame", b =>
                {
                    b.HasOne("Domain.BowlingGame", null)
                        .WithMany("Frames")
                        .HasForeignKey("BowlingGameId");
                });

            modelBuilder.Entity("Domain.BowlingGame", b =>
                {
                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
